version: '3.8'

services:
  app:
    image: openjdk:17-jdk-slim
    container_name: tdt-backend
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - .:/app
    working_dir: /app
    command: ["./mvnw", "spring-boot:run"]
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: tdt-db
    environment:
      POSTGRES_DB: TDT
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dothang3z
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: