spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/TDT
    username: postgres
    password: dothang3z
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: info
    org.springframework.security: trace

application:
  security:
    authentication:
      jwt:
        base64-secret: OhWwNOhKThUZT+0VUVfQyx6aJWcScDSecgPHfazq1XAMeckjJg+Yj8Guu1SaXH3bFpmbwlcqzFWLMWnAIhSsCz3EXytY1x3aBA07XQBwVNGAes/OD7BQYLIXmFdwCGdUFXHn0IgapXRQWCRWTLq1f/ZB9xUsnObY9CqLE1nPk46eD355MqwvDHMU5Lbd19/dFCFHlVS58xEE6AbudAnZpii65UTGVrcIIyNKmyM36238s98dY8TpqrejcMqttrn+xZnKyylG0it2HDo1JcdiqtNNlwnn/rbqiOtbKcRMetrOeoR6NEKKBmo33kX89dOzQVXwHaORxv8VdjOPzB0ilQ==
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: '*'
  third-party:
    google:
      client-id: 487748383748-n5ki1tvuo5hecg9u1ea0j13qpldi7ch4.apps.googleusercontent.com|487748383748-6ol7c9ejj32gnt596mfrmm9grng97528.apps.googleusercontent.com
      client-secret: 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
  otp:
    time-step-in-sec: 30
    result-validity-in-sec: 300
    length: 6
