--create table enum

DROP TABLE IF EXISTS public.roles CASCADE;
CREATE TABLE public.roles
(
    name varchar(50) NOT NULL,

    CONSTRAINT roles_pkey PRIMARY KEY (name)
);

-- create table schema

DROP TABLE IF EXISTS public.users CASCADE;
CREATE TABLE public.users
(
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    login varchar(255) NOT NULL,
    password_hash varchar(255) NOT NULL,
    phone_number varchar(15),
    first_name varchar(255) NOT NULL,
    source varchar(50) NOT NULL,
    last_name varchar(255) NOT NULL,
    email varchar(255),
    avatar varchar(255),
    secret_key varchar(255),
    reset_key varchar(255),
    created_at timestamp,
    deleted_at timestamp,
    updated_at timestamp,

    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT unique_login UNIQUE (login)
);

DROP TABLE IF EXISTS public.accounts CASCADE;
CREATE TABLE public.accounts
(
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    user_id int8 NOT NULL,
    role varchar(50) NOT NULL,
    created_at timestamp,
    deleted_at timestamp,
    updated_at timestamp,

    CONSTRAINT accounts_pkey PRIMARY KEY (id),
    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES public.users (id),
    CONSTRAINT fk_role FOREIGN KEY (role) REFERENCES public.roles (name)
);

DROP TABLE IF EXISTS public.classroom CASCADE;
CREATE TABLE public.classroom
(
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    code varchar(50) NOT NULL,
    name varchar NOT NULL,
    description varchar(1000),
    member_numbers int,
    admin_id int8 NOT NULL,
    type varchar(50) NOT NULL,
    date date NOT NULL,
    status varchar(50) NOT NULL,

    CONSTRAINT classroom_pkey PRIMARY KEY (id),
    CONSTRAINT fk_admin_id FOREIGN KEY (admin_id) REFERENCES public.accounts (id),
    CONSTRAINT fk_code UNIQUE (code)
);

DROP TABLE IF EXISTS public.teaching_assistant CASCADE;
CREATE TABLE public.teaching_assistant
(
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    user_id int8 NOT NULL,
    class_id int8 NOT NULL,
    created_at timestamp,
    deleted_at timestamp,
    updated_at timestamp,

    CONSTRAINT teaching_assistant_pkey PRIMARY KEY (id),
    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES public.accounts (id),
    CONSTRAINT fk_class_id FOREIGN KEY (class_id) REFERENCES public.classroom (id)
);

DROP TABLE IF EXISTS public.user_classroom_xref CASCADE;
CREATE TABLE public.user_classroom_xref
(
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    user_id int8 NOT NULL,
    class_id int8 NOT NULL,
    status varchar(50) NOT NULL,

    CONSTRAINT user_classroom_xref_pkey PRIMARY KEY (id),
    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES public.accounts (id),
    CONSTRAINT fk_class_id FOREIGN KEY (class_id) REFERENCES public.classroom (id)
);

DROP TABLE IF EXISTS public.exercise CASCADE;
CREATE TABLE public.exercise
(
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    title varchar(150) NOT NULL,
    description text ,
    class_id int8 NOT NULL,
    deadline timestamp NOT NULL,
    created_at timestamp,
    deleted_at timestamp,
    updated_at timestamp,

    CONSTRAINT exercise_pkey PRIMARY KEY (id),
    CONSTRAINT fk_class_id FOREIGN KEY (class_id) REFERENCES public.classroom (id)
);

DROP TABLE IF EXISTS public.exercise_submission CASCADE;
CREATE TABLE public.exercise_submission
(
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    exercise_id int8 NOT NULL,
    user_id int8 NOT NULL ,
    link_github text NOT NULL,
    description text,
    submitted_at timestamp NOT NULL,
    score varchar(20),
    comment text,
    created_at timestamp,
    deleted_at timestamp,
    updated_at timestamp,

    CONSTRAINT exercise_submission_pkey PRIMARY KEY (id),
    CONSTRAINT fk_exercise_id FOREIGN KEY (exercise_id) REFERENCES public.exercise (id),
    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES public.accounts (id)
);

DROP TABLE IF EXISTS public.contacts_us CASCADE;
CREATE TABLE public.contacts_us
(
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    user_id int8 NOT NULL,
    message text NOT NULL,
    created_at timestamp,
    deleted_at timestamp,
    updated_at timestamp,

    CONSTRAINT contacts_us_pkey PRIMARY KEY (id),
    CONSTRAINT fk_account_id FOREIGN KEY (user_id) REFERENCES public.accounts (id)
);

DROP TABLE IF EXISTS public.schedule CASCADE;
CREATE TABLE public.schedule
(
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    start_time time NOT NULL,
    end_time time NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    title varchar(100) NOT NULL,
    admin_id int8 NOT NULL ,
    class_id int8 NOT NULL,
    description text,
    created_at timestamp,
    deleted_at timestamp,
    updated_at timestamp,

    CONSTRAINT classroom_schedule_pkey PRIMARY KEY (id),
    CONSTRAINT fk_admin_id FOREIGN KEY (admin_id) REFERENCES public.accounts (id),
    CONSTRAINT fk_class_id FOREIGN KEY (class_id) REFERENCES public.classroom (id)
);